spring:
  config:
    import: optional:file:.env[.properties] # 環境変数は.envの内容を参照する。
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/common
jwt:
  secret: ${JWT_SECRET}