spring:
  datasource:
    url: jdbc:postgresql://elms-db:5432/elms_db
    username: root
    password: pass
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/default

jwt:
  secret: 0dTIXBDkSbhltNOJX8M3oMuN5K+vDG4Z7ZaY8rpg8kQ=